name: Threadfin
version: "1.2.37"
slug: threadfin
description: Threadfin - M3U proxy server for Plex, Emby and Jellyfin
url: https://github.com/Threadfin/Threadfin
image: fyb3roptik/threadfin
arch:
  - amd64
  - aarch64
init: false
host_network: true
map:
  - path: /home/threadfin/conf
    type: addon_config
    read_only: false
  - path: /home/threadfin/conf/backup
    type: addon_config
    read_only: false
  - path: /tmp/threadfin
    type: addon_config
    read_only: false
ports:
  34400/tcp: 34400
ports_description:
  34400/tcp: Threadfin Web UI
webui: http://[HOST]:[PORT:34400]
panel_icon: mdi:television
