name: Pi-hole
version: 2024.07.0
slug: pihole
description: Network-wide ads & trackers blocking DNS server
url: 
ingress: true
ingress_port: 0
ingress_stream: true
startup: services
arch:
  - aarch64
  - amd64
  - armv7
init: false
environment:
  WEBPASSWORD: "sua_senha_segura"
ports:
  53/udp: 53
  80/tcp: 80
ports_description:
  53/udp: DNS server port
  80/tcp: Web interface (Not required for Ingress)
discovery:
  - pihole
auth_api: true
host_network: true
hassio_api: true
hassio_role: manager
map:
  - config
  - ssl
  - addons
  - backup
  - share
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  password: "sua_senha_segura"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  password: str
  leave_front_door_open: bool?
image: "pihole/pihole"
