name: Pi-hole
version: "2024.07.0"
slug: pihole
description: "Network-wide Ad Blocking"
url: https://hub.docker.com/r/pihole/pihole
image: pihole/pihole
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
webui: http://[HOST]:[PORT:80]
ingress_port: 80
ingress_entry: /admin/
panel_icon: mdi:pi-hole
startup: system
ports:
  "53/tcp": 53
  "53/udp": 53
  "80/tcp": null
ports_description:
  "53/tcp": DNS server port
  "53/udp": DNS server port
  "80/tcp": UNPROTECTED web UI (not required for Ingress)
timeout: 60
options:
  dnscrypt: []
schema:
  dnscrypt:
    - name: str
      stamp: str
init: false
